#! /usr/bin/env lua

-- Copyright (C) 2015 Tomoyuki Fujimori <moyu@dromozoa.com>
--
-- This file is part of dromozoa-amalgamate.
--
-- dromozoa-amalgamate is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- dromozoa-amalgamate is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with dromozoa-amalgamate.  If not, see <http://www.gnu.org/licenses/>.

local json = require "dromozoa.commons.json"
local split = require "dromozoa.commons.split"
local dumper = require "dromozoa.commons.dumper"
local searchpath = require "dromozoa.commons.searchpath"
local sequence = require "dromozoa.commons.sequence"
local sequence_writer = require "dromozoa.commons.sequence_writer"
local pairs = require "dromozoa.commons.pairs"

local backup_require = require
local searchers = package.loaders or package.searchers
for i = 1, #searchers do
  print(i, searchers[i])
end
print(package.path)

local stack = sequence()

require = function (modname)
  io.write(("  "):rep(#stack), modname, "\n")
  stack:push(modname)
  local result = backup_require(modname)
  stack:pop()
  return result
end

local function wrap_searcher(modname, loader, filename, ...)
  if type(loader) == "function" then
    if filename == nil then
      filename = searchpath(modname, package.path)
    end
    if filename ~= nil and filename:match("%.lua$") then
      print(modname, filename)
    end
  end
  return loader, filename, ...
end

for k, v in pairs(searchers) do
  local searcher = searchers[k]
  searchers[k] = function (modname, ...)
    -- print("searcher", k, modname)
    return wrap_searcher(modname, searcher(modname, ...))
  end;
end

for i = 1, #arg do
  local modname = arg[i]
  require(modname)
end


